### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by Yushe** [chatpool-net/Instant-Noodles#1]
Bans don't work and users can see ips in plain text.

**Comment by chatpool-net** [comment]
Can you elaborate on bans not working?

**Comment by Yushe** [comment]
@chatpool-net Banned users can post and it won't even redirect them to a ban page.

**Comment by chatpool-net** [comment]
Interesting, I tested it on two different ips and it seemed to work fine, but ill test it some more.
![issue](https://cloud.githubusercontent.com/assets/17831918/14692739/3f666ce6-0727-11e6-8533-1f8946844c0d.PNG)



Also I'm working on hiding a portion of the ips so that board admins won't be able to view the full posters ip address. Thank you for making the issue.

**Comment by chatpool-net** [comment]
This is how ips will be hidden from now on
http://dis.chatpool.net/test/test.php

I'll close this issue once the feature has been pushed to the repo.

**Comment by chatpool-net** [comment]
Just realized that if you're logged in as board admin and posting normal and banned you'll still be able to post and I think that's whats happening to you. Board admins can't be banned unless logged out.
Also Ips are now hidden!

**Comment by Yushe** [comment]
@chatpool-net Also instant noodles is coded in such a way only the domain chatpool.net can use it.

**Comment by chatpool-net** [comment]
@Yushe Will work on that as well. The github repo is basically just a copy of chatpool right now so I plan on making it work on all sites without any tweaks. Currently you can still use the script by just changing the url in some of the files. Thank you for reporting these things!
